# General Jekyll Config
highlighter: rouge
url: https://pinedance.github.io
lsi: false
markdown: kramdown
exclude: [LICENSE, README.md, .gitignore, Gemfile, Gemfile.lock, _build.rb, _sandbox]

# Site Settings
baseurl:            "/shanghanlun" # Base URL must end WITHOUT a slash, default: ""
timezone:           Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Build settings
host: 0.0.0.0
port: 8384

# Plugins
plugins:
  - jekyll-redirect-from

# ref : https://jekyllrb.com/docs/collections/
collections:
  reference:
        output: true
        permalink:  /:collection/:path
        author: host
  lecture:
        output: true
        permalink:  /:collection/:path
        author: host

# Global Variables
formulaurl: "/shanghanlun/reference/Formulas"
herburl: "/shanghanlun/reference/Herbs"
sympurl: "/shanghanlun/reference/Symptoms"
slideurl: "/shanghanlun/lecture/Slides"

github: [metadata]
